// data/snippets/section/section.jsx
import React from 'react';

export default function section(){
  return (
    <>
      <main className="main-home">
      
        {/* HERO */}
      
        <section className="hero-section">
      
          <div className="hero-badge">
            ✦ Premium Website Layouts
          </div>
      
          <h1>
            Modern <span>Website Sections</span>
          </h1>
      
          <p>
      
            Discover premium reusable website
            sections crafted for modern interfaces.
            Hero blocks, pricing layouts, stats,
            testimonials and more.
      
          </p>
      
        </section>
      
        {/* FILTER */}
      
        <section className="filter-bar">
      
          <button className="filter-btn active">
            All
          </button>
      
          <button className="filter-btn">
            Hero
          </button>
      
          <button className="filter-btn">
            Pricing
          </button>
      
          <button className="filter-btn">
            Stats
          </button>
      
          <button className="filter-btn">
            Features
          </button>
      
        </section>
      
        {/* MODERN SECTION COMPONENTS */}
      
      {/* CARD */}
      <div className="section-card premium-card">
      
        <div className="section-icon gradient-purple">
          🚀
        </div>
      
        <span className="card-tag">
          STARTUP
        </span>
      
        <h2>Startup Sections</h2>
      
        <p>
          Modern startup landing page layouts with animated UI and bold typography.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card premium-card">
      
        <div className="section-icon gradient-blue">
          💳
        </div>
      
        <span className="card-tag">
          FINTECH
        </span>
      
        <h2>Fintech Sections</h2>
      
        <p>
          Banking, payment and financial dashboard layouts with premium UI design.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card premium-card">
      
        <div className="section-icon gradient-pink">
          🛍️
        </div>
      
        <span className="card-tag">
          SHOPPING
        </span>
      
        <h2>Storefront Sections</h2>
      
        <p>
          Modern storefront and product discovery sections for online brands.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card premium-card">
      
        <div className="section-icon gradient-green">
          🧑‍💻
        </div>
      
        <span className="card-tag">
          SAAS
        </span>
      
        <h2>SaaS Sections</h2>
      
        <p>
          SaaS dashboard and software showcase layouts with modern UX patterns.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card premium-card">
      
        <div className="section-icon gradient-orange">
          🎬
        </div>
      
        <span className="card-tag">
          MEDIA
        </span>
      
        <h2>Streaming Sections</h2>
      
        <p>
          Netflix-inspired media layouts with cinematic cards and hero banners.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card premium-card">
      
        <div className="section-icon gradient-cyan">
          📈
        </div>
      
        <span className="card-tag">
          BUSINESS
        </span>
      
        <h2>Growth Sections</h2>
      
        <p>
          KPI and growth showcase layouts with modern analytics inspired design.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card premium-card">
      
        <div className="section-icon gradient-red">
          🏢
        </div>
      
        <span className="card-tag">
          CORPORATE
        </span>
      
        <h2>Corporate Sections</h2>
      
        <p>
          Elegant enterprise and business layouts built for professional brands.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card premium-card">
      
        <div className="section-icon gradient-gold">
          🎓
        </div>
      
        <span className="card-tag">
          EDUCATION
        </span>
      
        <h2>Learning Sections</h2>
      
        <p>
          Online course and education layouts with modern interactive UI blocks.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card premium-card">
      
        <div className="section-icon gradient-dark">
          🌌
        </div>
      
        <span className="card-tag">
          FUTURE UI
        </span>
      
        <h2>Cyberpunk Sections</h2>
      
        <p>
          Futuristic neon-inspired layouts for gaming and AI interfaces.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card premium-card">
      
        <div className="section-icon gradient-sky">
          ☁️
        </div>
      
        <span className="card-tag">
          CLOUD
        </span>
      
        <h2>Cloud Sections</h2>
      
        <p>
          Cloud platform and hosting layouts with premium glassmorphism styling.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card premium-card">
      
        <div className="section-icon gradient-violet">
          📦
        </div>
      
        <span className="card-tag">
          PRODUCT
        </span>
      
        <h2>Product Launch</h2>
      
        <p>
          Product announcement and feature release layouts for modern startups.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card premium-card">
      
        <div className="section-icon gradient-lime">
          🌿
        </div>
      
        <span className="card-tag">
          ECO
        </span>
      
        <h2>Eco Sections</h2>
      
        <p>
          Sustainable and eco-friendly brand sections with clean modern design.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
        {/* GRID */}
      
        <section className="sections-grid">
      
          {/* CARD */}
      
          <div className="section-card">
      
            <div className="card-icon orange">
              🚀
            </div>
      
            <span className="card-label">
              HERO
            </span>
      
            <h2>
              Hero Sections
            </h2>
      
            <p>
      
              Premium landing page hero
              layouts with modern typography,
              gradients and CTA buttons.
      
            </p>
      
            <button>
              View Section
            </button>
      
          </div>
      
          {/* ADD THESE NEW COMPONENTS INSIDE .sections-container */}
      
      {/* CARD */}
      <div className="section-card">
      
        <div className="section-icon">
          🛒
        </div>
      
        <h2>E-Commerce Sections</h2>
      
        <p>
          Product showcase and shopping UI layouts.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card">
      
        <div className="section-icon">
          🎨
        </div>
      
        <h2>Portfolio Sections</h2>
      
        <p>
          Creative portfolio layouts for designers and developers.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card">
      
        <div className="section-icon">
          📱
        </div>
      
        <h2>App Showcase</h2>
      
        <p>
          Mobile app presentation and download sections.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card">
      
        <div className="section-icon">
          🧠
        </div>
      
        <h2>AI Sections</h2>
      
        <p>
          Futuristic AI startup and chatbot website layouts.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card">
      
        <div className="section-icon">
          🎥
        </div>
      
        <h2>Video Sections</h2>
      
        <p>
          Video showcase blocks with modern media layouts.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card">
      
        <div className="section-icon">
          📰
        </div>
      
        <h2>Blog Sections</h2>
      
        <p>
          Responsive article and blog listing layouts.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card">
      
        <div className="section-icon">
          📅
        </div>
      
        <h2>Event Sections</h2>
      
        <p>
          Event schedule and conference landing sections.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card">
      
        <div className="section-icon">
          🔐
        </div>
      
        <h2>Authentication</h2>
      
        <p>
          Login, signup and password recovery sections.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card">
      
        <div className="section-icon">
          🌍
        </div>
      
        <h2>Travel Sections</h2>
      
        <p>
          Tourism and travel destination website layouts.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card">
      
        <div className="section-icon">
          🏆
        </div>
      
        <h2>Achievement Sections</h2>
      
        <p>
          Awards, milestones and company achievement blocks.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card">
      
        <div className="section-icon">
          🎯
        </div>
      
        <h2>CTA Sections</h2>
      
        <p>
          High-converting call-to-action website sections.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
      {/* CARD */}
      <div className="section-card">
      
        <div className="section-icon">
          ⚡
        </div>
      
        <h2>Service Sections</h2>
      
        <p>
          Professional service showcase layouts for agencies.
        </p>
      
        <a href="#">
          View Section
        </a>
      
      </div>
      
          {/* CARD */}
      
          <div className="section-card">
      
            <div className="card-icon purple">
              💼
            </div>
      
            <span className="card-label">
              PRICING
            </span>
      
            <h2>
              Pricing Sections
            </h2>
      
            <p>
      
              Responsive SaaS pricing layouts
              with premium UI cards and
              subscription tables.
      
            </p>
      
            <button>
              View Section
            </button>
      
          </div>
      
          {/* CARD */}
      
          <div className="section-card">
      
            <div className="card-icon blue">
              ⭐
            </div>
      
            <span className="card-label">
              TESTIMONIALS
            </span>
      
            <h2>
              Testimonial Blocks
            </h2>
      
            <p>
      
              Beautiful review and feedback
              sections with glassmorphism
              inspired layouts.
      
            </p>
      
            <button>
              View Section
            </button>
      
          </div>
      
          {/* CARD */}
      
          <div className="section-card">
      
            <div className="card-icon green">
              📊
            </div>
      
            <span className="card-label">
              STATS
            </span>
      
            <h2>
              Analytics Sections
            </h2>
      
            <p>
      
              Dashboard analytics and stats
              layouts for admin interfaces
              and SaaS dashboards.
      
            </p>
      
            <button>
              View Section
            </button>
      
          </div>
      
          {/* CARD */}
      
          <div className="section-card">
      
            <div className="card-icon orange">
              📩
            </div>
      
            <span className="card-label">
              NEWSLETTER
            </span>
      
            <h2>
              Newsletter Sections
            </h2>
      
            <p>
      
              Responsive email subscribe
              sections crafted with modern
              glassmorphism UI.
      
            </p>
      
            <button>
              View Section
            </button>
      
          </div>
      
          {/* CARD */}
      
          <div className="section-card">
      
            <div className="card-icon purple">
              🧩
            </div>
      
            <span className="card-label">
              FEATURES
            </span>
      
            <h2>
              Feature Blocks
            </h2>
      
            <p>
      
              Showcase product features
              with premium modern
              layout sections.
      
            </p>
      
            <button>
              View Section
            </button>
      
          </div>
      
        </section>
      
      </main>
    </>
  );
}

// data/snippets/section/section.vue
<template>
<main class="main-home">

  <!-- HERO -->

  <section class="hero-section">

    <div class="hero-badge">
      ✦ Premium Website Layouts
    </div>

    <h1>
      Modern <span>Website Sections</span>
    </h1>

    <p>

      Discover premium reusable website
      sections crafted for modern interfaces.
      Hero blocks, pricing layouts, stats,
      testimonials and more.

    </p>

  </section>

  <!-- FILTER -->

  <section class="filter-bar">

    <button class="filter-btn active">
      All
    </button>

    <button class="filter-btn">
      Hero
    </button>

    <button class="filter-btn">
      Pricing
    </button>

    <button class="filter-btn">
      Stats
    </button>

    <button class="filter-btn">
      Features
    </button>

  </section>

  <!-- MODERN SECTION COMPONENTS -->

<!-- CARD -->
<div class="section-card premium-card">

  <div class="section-icon gradient-purple">
    🚀
  </div>

  <span class="card-tag">
    STARTUP
  </span>

  <h2>Startup Sections</h2>

  <p>
    Modern startup landing page layouts with animated UI and bold typography.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card premium-card">

  <div class="section-icon gradient-blue">
    💳
  </div>

  <span class="card-tag">
    FINTECH
  </span>

  <h2>Fintech Sections</h2>

  <p>
    Banking, payment and financial dashboard layouts with premium UI design.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card premium-card">

  <div class="section-icon gradient-pink">
    🛍️
  </div>

  <span class="card-tag">
    SHOPPING
  </span>

  <h2>Storefront Sections</h2>

  <p>
    Modern storefront and product discovery sections for online brands.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card premium-card">

  <div class="section-icon gradient-green">
    🧑‍💻
  </div>

  <span class="card-tag">
    SAAS
  </span>

  <h2>SaaS Sections</h2>

  <p>
    SaaS dashboard and software showcase layouts with modern UX patterns.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card premium-card">

  <div class="section-icon gradient-orange">
    🎬
  </div>

  <span class="card-tag">
    MEDIA
  </span>

  <h2>Streaming Sections</h2>

  <p>
    Netflix-inspired media layouts with cinematic cards and hero banners.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card premium-card">

  <div class="section-icon gradient-cyan">
    📈
  </div>

  <span class="card-tag">
    BUSINESS
  </span>

  <h2>Growth Sections</h2>

  <p>
    KPI and growth showcase layouts with modern analytics inspired design.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card premium-card">

  <div class="section-icon gradient-red">
    🏢
  </div>

  <span class="card-tag">
    CORPORATE
  </span>

  <h2>Corporate Sections</h2>

  <p>
    Elegant enterprise and business layouts built for professional brands.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card premium-card">

  <div class="section-icon gradient-gold">
    🎓
  </div>

  <span class="card-tag">
    EDUCATION
  </span>

  <h2>Learning Sections</h2>

  <p>
    Online course and education layouts with modern interactive UI blocks.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card premium-card">

  <div class="section-icon gradient-dark">
    🌌
  </div>

  <span class="card-tag">
    FUTURE UI
  </span>

  <h2>Cyberpunk Sections</h2>

  <p>
    Futuristic neon-inspired layouts for gaming and AI interfaces.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card premium-card">

  <div class="section-icon gradient-sky">
    ☁️
  </div>

  <span class="card-tag">
    CLOUD
  </span>

  <h2>Cloud Sections</h2>

  <p>
    Cloud platform and hosting layouts with premium glassmorphism styling.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card premium-card">

  <div class="section-icon gradient-violet">
    📦
  </div>

  <span class="card-tag">
    PRODUCT
  </span>

  <h2>Product Launch</h2>

  <p>
    Product announcement and feature release layouts for modern startups.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card premium-card">

  <div class="section-icon gradient-lime">
    🌿
  </div>

  <span class="card-tag">
    ECO
  </span>

  <h2>Eco Sections</h2>

  <p>
    Sustainable and eco-friendly brand sections with clean modern design.
  </p>

  <a href="#">
    View Section
  </a>

</div>

  <!-- GRID -->

  <section class="sections-grid">

    <!-- CARD -->

    <div class="section-card">

      <div class="card-icon orange">
        🚀
      </div>

      <span class="card-label">
        HERO
      </span>

      <h2>
        Hero Sections
      </h2>

      <p>

        Premium landing page hero
        layouts with modern typography,
        gradients and CTA buttons.

      </p>

      <button>
        View Section
      </button>

    </div>

    <!-- ADD THESE NEW COMPONENTS INSIDE .sections-container -->

<!-- CARD -->
<div class="section-card">

  <div class="section-icon">
    🛒
  </div>

  <h2>E-Commerce Sections</h2>

  <p>
    Product showcase and shopping UI layouts.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card">

  <div class="section-icon">
    🎨
  </div>

  <h2>Portfolio Sections</h2>

  <p>
    Creative portfolio layouts for designers and developers.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card">

  <div class="section-icon">
    📱
  </div>

  <h2>App Showcase</h2>

  <p>
    Mobile app presentation and download sections.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card">

  <div class="section-icon">
    🧠
  </div>

  <h2>AI Sections</h2>

  <p>
    Futuristic AI startup and chatbot website layouts.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card">

  <div class="section-icon">
    🎥
  </div>

  <h2>Video Sections</h2>

  <p>
    Video showcase blocks with modern media layouts.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card">

  <div class="section-icon">
    📰
  </div>

  <h2>Blog Sections</h2>

  <p>
    Responsive article and blog listing layouts.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card">

  <div class="section-icon">
    📅
  </div>

  <h2>Event Sections</h2>

  <p>
    Event schedule and conference landing sections.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card">

  <div class="section-icon">
    🔐
  </div>

  <h2>Authentication</h2>

  <p>
    Login, signup and password recovery sections.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card">

  <div class="section-icon">
    🌍
  </div>

  <h2>Travel Sections</h2>

  <p>
    Tourism and travel destination website layouts.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card">

  <div class="section-icon">
    🏆
  </div>

  <h2>Achievement Sections</h2>

  <p>
    Awards, milestones and company achievement blocks.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card">

  <div class="section-icon">
    🎯
  </div>

  <h2>CTA Sections</h2>

  <p>
    High-converting call-to-action website sections.
  </p>

  <a href="#">
    View Section
  </a>

</div>

<!-- CARD -->
<div class="section-card">

  <div class="section-icon">
    ⚡
  </div>

  <h2>Service Sections</h2>

  <p>
    Professional service showcase layouts for agencies.
  </p>

  <a href="#">
    View Section
  </a>

</div>

    <!-- CARD -->

    <div class="section-card">

      <div class="card-icon purple">
        💼
      </div>

      <span class="card-label">
        PRICING
      </span>

      <h2>
        Pricing Sections
      </h2>

      <p>

        Responsive SaaS pricing layouts
        with premium UI cards and
        subscription tables.

      </p>

      <button>
        View Section
      </button>

    </div>

    <!-- CARD -->

    <div class="section-card">

      <div class="card-icon blue">
        ⭐
      </div>

      <span class="card-label">
        TESTIMONIALS
      </span>

      <h2>
        Testimonial Blocks
      </h2>

      <p>

        Beautiful review and feedback
        sections with glassmorphism
        inspired layouts.

      </p>

      <button>
        View Section
      </button>

    </div>

    <!-- CARD -->

    <div class="section-card">

      <div class="card-icon green">
        📊
      </div>

      <span class="card-label">
        STATS
      </span>

      <h2>
        Analytics Sections
      </h2>

      <p>

        Dashboard analytics and stats
        layouts for admin interfaces
        and SaaS dashboards.

      </p>

      <button>
        View Section
      </button>

    </div>

    <!-- CARD -->

    <div class="section-card">

      <div class="card-icon orange">
        📩
      </div>

      <span class="card-label">
        NEWSLETTER
      </span>

      <h2>
        Newsletter Sections
      </h2>

      <p>

        Responsive email subscribe
        sections crafted with modern
        glassmorphism UI.

      </p>

      <button>
        View Section
      </button>

    </div>

    <!-- CARD -->

    <div class="section-card">

      <div class="card-icon purple">
        🧩
      </div>

      <span class="card-label">
        FEATURES
      </span>

      <h2>
        Feature Blocks
      </h2>

      <p>

        Showcase product features
        with premium modern
        layout sections.

      </p>

      <button>
        View Section
      </button>

    </div>

  </section>

</main>
</template>

<script>
export default { name: 'Section' }
</script>
