// data/snippets/pricing/pricing.vue
<template>
<main class="main-home">


  <!-- ================= PRICING HERO ================= -->

<div class="pricing-page-hero">

  <div class="breadcrumb">
    <a href="index.html">Home</a>
    <i class="fa-solid fa-chevron-right"></i>
    <span>Pricing</span>
  </div>

  <h1 class="page-title">
    Pricing Card Components
  </h1>

  <p class="page-desc">
    Modern SaaS pricing UI components with billing toggles,
    glowing cards, feature lists, and responsive layouts.
  </p>

  <div class="page-meta">

    <span class="meta-badge">
      <i class="fa-solid fa-layer-group"></i>
      3 Plans
    </span>

    <span class="meta-badge">
      <i class="fa-solid fa-toggle-on"></i>
      Billing Toggle
    </span>

    <span class="meta-badge">
      <i class="fa-solid fa-code"></i>
      HTML + CSS
    </span>

  </div>

</div>


<!-- ================= GLASSMORPHISM PRICING ================= -->

<div class="component-card">

  <div class="glass-pricing-grid">

    <!-- BASIC -->
    <div class="glass-card">

      <div class="glass-top">
        <span class="glass-plan">Basic</span>
        <h2>$9</h2>
        <p>/ month</p>
      </div>

      <ul class="glass-features">
        <li><i class="fa-solid fa-check"></i> 5 Projects</li>
        <li><i class="fa-solid fa-check"></i> Email Support</li>
        <li><i class="fa-solid fa-check"></i> Analytics</li>
      </ul>

      <button class="glass-btn">
        Start Free
      </button>

    </div>

    <!-- TEAM -->
    <div class="glass-card featured-glass">

      <div class="popular-pill">
        Recommended
      </div>

      <div class="glass-top">
        <span class="glass-plan">Team</span>
        <h2>$29</h2>
        <p>/ month</p>
      </div>

      <ul class="glass-features">
        <li><i class="fa-solid fa-check"></i> Unlimited Projects</li>
        <li><i class="fa-solid fa-check"></i> Team Access</li>
        <li><i class="fa-solid fa-check"></i> Priority Support</li>
        <li><i class="fa-solid fa-check"></i> API Access</li>
      </ul>

      <button class="glass-btn active-btn">
        Get Team Plan
      </button>

    </div>

    <!-- AGENCY -->
    <div class="glass-card">

      <div class="glass-top">
        <span class="glass-plan">Agency</span>
        <h2>$79</h2>
        <p>/ month</p>
      </div>

      <ul class="glass-features">
        <li><i class="fa-solid fa-check"></i> White Label</li>
        <li><i class="fa-solid fa-check"></i> Unlimited Users</li>
        <li><i class="fa-solid fa-check"></i> Dedicated Manager</li>
      </ul>

      <button class="glass-btn">
        Contact Us
      </button>

    </div>

  </div>

</div>

<!-- ================= NEON PRICING ================= -->

<div class="component-card">

  <div class="neon-pricing-grid">

    <!-- SILVER -->
    <div class="neon-card silver">

      <h3>Silver</h3>

      <div class="neon-price">
        $15
      </div>

      <p class="neon-desc">
        Great for freelancers
      </p>

      <ul>
        <li>5 GB Storage</li>
        <li>Custom Domain</li>
        <li>Email Support</li>
      </ul>

      <button class="neon-btn">
        Select Plan
      </button>

    </div>

    <!-- GOLD -->
    <div class="neon-card gold">

      <div class="neon-badge">
        <i class="fa-solid fa-crown"></i>
        BEST VALUE
      </div>

      <h3>Gold</h3>

      <div class="neon-price">
        $49
      </div>

      <p class="neon-desc">
        Ideal for startups
      </p>

      <ul>
        <li>Unlimited Storage</li>
        <li>AI Analytics</li>
        <li>24/7 Support</li>
      </ul>

      <button class="neon-btn active-neon">
        Choose Gold
      </button>

    </div>

    <!-- PLATINUM -->
    <div class="neon-card platinum">

      <h3>Platinum</h3>

      <div class="neon-price">
        $99
      </div>

      <p class="neon-desc">
        Enterprise solution
      </p>

      <ul>
        <li>Unlimited Everything</li>
        <li>Dedicated Manager</li>
        <li>Custom Integrations</li>
      </ul>

      <button class="neon-btn">
        Contact Sales
      </button>

    </div>

  </div>

</div>

<!-- ================= MINIMAL PRICING ================= -->

<div class="component-card">

  <div class="minimal-pricing-grid">

    <!-- LITE -->
    <div class="minimal-card">

      <span class="mini-label">
        Lite
      </span>

      <h2>$5</h2>

      <p>
        Small personal websites
      </p>

      <button class="minimal-btn">
        Buy Now
      </button>

    </div>

    <!-- PLUS -->
    <div class="minimal-card dark-mini">

      <span class="mini-label">
        Plus
      </span>

      <h2>$19</h2>

      <p>
        Best for professionals
      </p>

      <button class="minimal-btn light-btn">
        Choose Plus
      </button>

    </div>

    <!-- ULTRA -->
    <div class="minimal-card">

      <span class="mini-label">
        Ultra
      </span>

      <h2>$59</h2>

      <p>
        Built for agencies
      </p>

      <button class="minimal-btn">
        Upgrade
      </button>

    </div>

  </div>

</div>
<!-- ================= COMPONENT CARD ================= -->

<div class="component-card">

  <!-- TOP -->

  <div class="card-top">

    <div>
      <h2 class="card-label">
        Interactive Pricing Table
      </h2>
    </div>

    <span class="card-tag">
      Popular
    </span>

  </div>

  <!-- DESCRIPTION -->

  <p class="card-desc">
    Fully responsive SaaS pricing section with
    monthly, quarterly, and yearly billing toggle.
  </p>

  <!-- ================= TOGGLE ================= -->

  <div class="billing-toggle-wrap">

    <div class="billing-toggle">

      <button class="toggle-btn active"
        data-period="month">

        Monthly

      </button>

      <button class="toggle-btn"
        data-period="quarter">

        Quarterly

      </button>

      <button class="toggle-btn"
        data-period="year">

        Yearly

        <span class="save-chip">
          Save 40%
        </span>

      </button>

    </div>

  </div>

  <!-- ================= PRICING GRID ================= -->

  <div class="pricing-grid-preview">

    <!-- FREE -->

    <div class="plan-card free-card">

      <div class="plan-name">
        Free
      </div>

      <p class="plan-tagline">
        For hobby projects
      </p>

      <div class="plan-price-wrap">

        <span class="plan-amount"
          data-month="$0"
          data-quarter="$0"
          data-year="$0">

          $0

        </span>

        <span class="plan-period">
          / month
        </span>

      </div>

      <ul class="plan-features">

        <li>
          <i class="fa-solid fa-check"></i>
          3 Projects
        </li>

        <li>
          <i class="fa-solid fa-check"></i>
          Community Support
        </li>

        <li>
          <i class="fa-solid fa-check"></i>
          Basic Analytics
        </li>

        <li class="muted">
          <i class="fa-solid fa-xmark"></i>
          Custom Domains
        </li>

        <li class="muted">
          <i class="fa-solid fa-xmark"></i>
          Priority Support
        </li>

      </ul>

      <button class="plan-btn plan-btn-outline">
        Get Started
      </button>

    </div>

    <!-- PRO -->

    <div class="plan-card pro-card">

      <div class="recommended-badge">

        <i class="fa-solid fa-star"></i>

        Most Popular

      </div>

      <div class="plan-name">
        Pro
      </div>

      <p class="plan-tagline">
        Best for growing startups
      </p>

      <div class="plan-price-wrap">

        <span class="plan-old"
          data-month="$49"
          data-quarter="$44"
          data-year="$39">

          $49

        </span>

        <span class="plan-amount"
          data-month="$29"
          data-quarter="$26"
          data-year="$19">

          $29

        </span>

        <span class="plan-period">
          / month
        </span>

      </div>

      <ul class="plan-features">

        <li>
          <i class="fa-solid fa-check"></i>
          Unlimited Projects
        </li>

        <li>
          <i class="fa-solid fa-check"></i>
          Team Collaboration
        </li>

        <li>
          <i class="fa-solid fa-check"></i>
          Priority Support
        </li>

        <li>
          <i class="fa-solid fa-check"></i>
          Custom Domains
        </li>

        <li class="muted">
          <i class="fa-solid fa-xmark"></i>
          White Label
        </li>

      </ul>

      <button class="plan-btn plan-btn-accent">
        Choose Pro
      </button>

    </div>

    <!-- ENTERPRISE -->

    <div class="plan-card enterprise-card">

      <div class="plan-name">
        Enterprise
      </div>

      <p class="plan-tagline">
        For large organizations
      </p>

      <div class="plan-price-wrap">

        <span class="plan-old"
          data-month="$149"
          data-quarter="$134"
          data-year="$119">

          $149

        </span>

        <span class="plan-amount"
          data-month="$99"
          data-quarter="$89"
          data-year="$69">

          $99

        </span>

        <span class="plan-period">
          / month
        </span>

      </div>

      <ul class="plan-features">

        <li>
          <i class="fa-solid fa-check"></i>
          Dedicated Manager
        </li>

        <li>
          <i class="fa-solid fa-check"></i>
          White Label
        </li>

        <li>
          <i class="fa-solid fa-check"></i>
          SLA Guarantee
        </li>

        <li>
          <i class="fa-solid fa-check"></i>
          Custom Integrations
        </li>

        <li>
          <i class="fa-solid fa-check"></i>
          Unlimited Storage
        </li>

      </ul>

      <button class="plan-btn business-btn">
        Contact Sales
      </button>

    </div>

  </div>

  <!-- ================= ACTION BUTTONS ================= -->

  <div class="actions">

    <button class="action-btn view-btn"
      onclick="toggleCode('pc1', this)">

      <i class="fa-solid fa-code"></i>
      View Code

    </button>

    <button class="action-btn copy-btn"
      onclick="copyCode('pc1', this)">

      <i class="fa-solid fa-copy"></i>
      Copy

    </button>

  </div>

  <!-- ================= CODE BLOCK ================= -->

  <pre id="pc1" class="code-block"><code>

&lt;div class="pricing-grid-preview"&gt;

  &lt;div class="plan-card free-card"&gt;&lt;/div&gt;

  &lt;div class="plan-card pro-card"&gt;&lt;/div&gt;

  &lt;div class="plan-card enterprise-card"&gt;&lt;/div&gt;

&lt;/div&gt;

  </code></pre>

</div>
  

  <!-- ================= ACTION BUTTONS ================= -->

  <div class="actions">

    <button class="action-btn view-btn"
      onclick="toggleCode('pc1', this)">

      <i class="fa-solid fa-code"></i>
      View Code

    </button>

    <button class="action-btn copy-btn"
      onclick="copyCode('pc1', this)">

      <i class="fa-solid fa-copy"></i>
      Copy

    </button>

  </div>

  <!-- ================= CODE BLOCK ================= -->

  <pre id="pc1" class="code-block"><code>

&lt;div class="pricing-grid-preview"&gt;

  &lt;div class="plan-card free-card"&gt;
    ...
  &lt;/div&gt;

  &lt;div class="plan-card pro-card"&gt;
    ...
  &lt;/div&gt;

  &lt;div class="plan-card enterprise-card"&gt;
    ...
  &lt;/div&gt;

&lt;/div&gt;

  </code></pre>

</div>

<!-- ================= SECOND COMPONENT ================= -->

<div class="component-card">

  <div class="pricing-grid">

    <!-- STARTER -->
    <div class="pricing-card starter">

      <div class="card-glow"></div>

      <div class="pricing-card-content">

        <div class="plan-header">
          <h3>Starter</h3>
          <p>Perfect for personal projects</p>
        </div>

        <div class="plan-price">
          <span class="old-price">$19</span>
          <span class="amount">$12</span>
        </div>

        <ul class="plan-features">
          <li><i class="fa-solid fa-check"></i> Basic analytics</li>
          <li><i class="fa-solid fa-check"></i> Custom domains</li>
          <li><i class="fa-solid fa-check"></i> Email support</li>
        </ul>

        <button class="plan-btn">
          Choose Starter
        </button>

      </div>
    </div>

    <!-- PRO -->
    <div class="pricing-card pro featured">

      <div class="popular-badge">
        Most Popular
      </div>

      <div class="card-glow"></div>

      <div class="pricing-card-content">

        <div class="plan-header">
          <h3>Pro</h3>
          <p>Best for scaling your business</p>
        </div>

        <div class="plan-price">
          <span class="old-price">$49</span>
          <span class="amount">$29</span>
        </div>

        <ul class="plan-features">
          <li><i class="fa-solid fa-check"></i> Advanced analytics</li>
          <li><i class="fa-solid fa-check"></i> Unlimited projects</li>
          <li><i class="fa-solid fa-check"></i> Priority support</li>
          <li><i class="fa-solid fa-check"></i> Team collaboration</li>
        </ul>

        <button class="plan-btn secondary">
          Choose Pro
        </button>

      </div>
    </div>

    <!-- BUSINESS -->
    <div class="pricing-card business">

      <div class="card-glow"></div>

      <div class="pricing-card-content">

        <div class="plan-header">
          <h3>Business</h3>
          <p>For growing startups & teams</p>
    

        <div class="plan-price">
          <span class="old-price">$99</span>
          <span class="amount">$59</span>
        </div>

        <ul class="plan-features">
          <li><i class="fa-solid fa-check"></i> AI-powered insights</li>
          <li><i class="fa-solid fa-check"></i> Unlimited storage</li>
          <li><i class="fa-solid fa-check"></i> Dedicated manager</li>
          <li><i class="fa-solid fa-check"></i> 24/7 live support</li>
        </ul>

        <button class="plan-btn business-btn">
          Choose Business
        </button>

      </div>
    </div>

  </div>

  <!-- ACTIONS -->
  <div class="actions">

    <button class="action-btn view-btn"
      onclick="toggleCode('pc2', this)">

      <i class="fa-solid fa-code"></i>
      View Code

    </button>

    <button class="action-btn copy-btn"
      onclick="copyCode('pc2', this)">

      <i class="fa-solid fa-copy"></i>
      Copy

    </button>

  </div>

  <!-- CODE -->
  <pre id="pc2" class="code-block"><code>

&lt;div class="pricing-grid"&gt;

  &lt;div class="pricing-card starter"&gt;
    ...
  &lt;/div&gt;

  &lt;div class="pricing-card pro"&gt;
    ...
  &lt;/div&gt;

  &lt;div class="pricing-card business"&gt;
    ...
  &lt;/div&gt;

&lt;/div&gt;

  </code></pre>

</div>
 <!-- /pricing-grid-preview -->

    
  

</main>
</template>

<script>
export default { name: 'Pricing' }
</script>

// data/snippets/pricing/pricing.jsx
import React from 'react';

export default function pricing(){
  return (
    <>
      <main className="main-home">
      
      
        {/* ================= PRICING HERO ================= */}
      
      <div className="pricing-page-hero">
      
        <div className="breadcrumb">
          <a href="index.html">Home</a>
          <i className="fa-solid fa-chevron-right"></i>
          <span>Pricing</span>
        </div>
      
        <h1 className="page-title">
          Pricing Card Components
        </h1>
      
        <p className="page-desc">
          Modern SaaS pricing UI components with billing toggles,
          glowing cards, feature lists, and responsive layouts.
        </p>
      
        <div className="page-meta">
      
          <span className="meta-badge">
            <i className="fa-solid fa-layer-group"></i>
            3 Plans
          </span>
      
          <span className="meta-badge">
            <i className="fa-solid fa-toggle-on"></i>
            Billing Toggle
          </span>
      
          <span className="meta-badge">
            <i className="fa-solid fa-code"></i>
            HTML + CSS
          </span>
      
        </div>
      
      </div>
      
      
      {/* ================= GLASSMORPHISM PRICING ================= */}
      
      <div className="component-card">
      
        <div className="glass-pricing-grid">
      
          {/* BASIC */}
          <div className="glass-card">
      
            <div className="glass-top">
              <span className="glass-plan">Basic</span>
              <h2>$9</h2>
              <p>/ month</p>
            </div>
      
            <ul className="glass-features">
              <li><i className="fa-solid fa-check"></i> 5 Projects</li>
              <li><i className="fa-solid fa-check"></i> Email Support</li>
              <li><i className="fa-solid fa-check"></i> Analytics</li>
            </ul>
      
            <button className="glass-btn">
              Start Free
            </button>
      
          </div>
      
          {/* TEAM */}
          <div className="glass-card featured-glass">
      
            <div className="popular-pill">
              Recommended
            </div>
      
            <div className="glass-top">
              <span className="glass-plan">Team</span>
              <h2>$29</h2>
              <p>/ month</p>
            </div>
      
            <ul className="glass-features">
              <li><i className="fa-solid fa-check"></i> Unlimited Projects</li>
              <li><i className="fa-solid fa-check"></i> Team Access</li>
              <li><i className="fa-solid fa-check"></i> Priority Support</li>
              <li><i className="fa-solid fa-check"></i> API Access</li>
            </ul>
      
            <button className="glass-btn active-btn">
              Get Team Plan
            </button>
      
          </div>
      
          {/* AGENCY */}
          <div className="glass-card">
      
            <div className="glass-top">
              <span className="glass-plan">Agency</span>
              <h2>$79</h2>
              <p>/ month</p>
            </div>
      
            <ul className="glass-features">
              <li><i className="fa-solid fa-check"></i> White Label</li>
              <li><i className="fa-solid fa-check"></i> Unlimited Users</li>
              <li><i className="fa-solid fa-check"></i> Dedicated Manager</li>
            </ul>
      
            <button className="glass-btn">
              Contact Us
            </button>
      
          </div>
      
        </div>
      
      </div>
      
      {/* ================= NEON PRICING ================= */}
      
      <div className="component-card">
      
        <div className="neon-pricing-grid">
      
          {/* SILVER */}
          <div className="neon-card silver">
      
            <h3>Silver</h3>
      
            <div className="neon-price">
              $15
            </div>
      
            <p className="neon-desc">
              Great for freelancers
            </p>
      
            <ul>
              <li>5 GB Storage</li>
              <li>Custom Domain</li>
              <li>Email Support</li>
            </ul>
      
            <button className="neon-btn">
              Select Plan
            </button>
      
          </div>
      
          {/* GOLD */}
          <div className="neon-card gold">
      
            <div className="neon-badge">
              <i className="fa-solid fa-crown"></i>
              BEST VALUE
            </div>
      
            <h3>Gold</h3>
      
            <div className="neon-price">
              $49
            </div>
      
            <p className="neon-desc">
              Ideal for startups
            </p>
      
            <ul>
              <li>Unlimited Storage</li>
              <li>AI Analytics</li>
              <li>24/7 Support</li>
            </ul>
      
            <button className="neon-btn active-neon">
              Choose Gold
            </button>
      
          </div>
      
          {/* PLATINUM */}
          <div className="neon-card platinum">
      
            <h3>Platinum</h3>
      
            <div className="neon-price">
              $99
            </div>
      
            <p className="neon-desc">
              Enterprise solution
            </p>
      
            <ul>
              <li>Unlimited Everything</li>
              <li>Dedicated Manager</li>
              <li>Custom Integrations</li>
            </ul>
      
            <button className="neon-btn">
              Contact Sales
            </button>
      
          </div>
      
        </div>
      
      </div>
      
      {/* ================= MINIMAL PRICING ================= */}
      
      <div className="component-card">
      
        <div className="minimal-pricing-grid">
      
          {/* LITE */}
          <div className="minimal-card">
      
            <span className="mini-label">
              Lite
            </span>
      
            <h2>$5</h2>
      
            <p>
              Small personal websites
            </p>
      
            <button className="minimal-btn">
              Buy Now
            </button>
      
          </div>
      
          {/* PLUS */}
          <div className="minimal-card dark-mini">
      
            <span className="mini-label">
              Plus
            </span>
      
            <h2>$19</h2>
      
            <p>
              Best for professionals
            </p>
      
            <button className="minimal-btn light-btn">
              Choose Plus
            </button>
      
          </div>
      
          {/* ULTRA */}
          <div className="minimal-card">
      
            <span className="mini-label">
              Ultra
            </span>
      
            <h2>$59</h2>
      
            <p>
              Built for agencies
            </p>
      
            <button className="minimal-btn">
              Upgrade
            </button>
      
          </div>
      
        </div>
      
      </div>
      {/* ================= COMPONENT CARD ================= */}
      
      <div className="component-card">
      
        {/* TOP */}
      
        <div className="card-top">
      
          <div>
            <h2 className="card-label">
              Interactive Pricing Table
            </h2>
          </div>
      
          <span className="card-tag">
            Popular
          </span>
      
        </div>
      
        {/* DESCRIPTION */}
      
        <p className="card-desc">
          Fully responsive SaaS pricing section with
          monthly, quarterly, and yearly billing toggle.
        </p>
      
        {/* ================= TOGGLE ================= */}
      
        <div className="billing-toggle-wrap">
      
          <div className="billing-toggle">
      
            <button className="toggle-btn active"
              data-period="month">
      
              Monthly
      
            </button>
      
            <button className="toggle-btn"
              data-period="quarter">
      
              Quarterly
      
            </button>
      
            <button className="toggle-btn"
              data-period="year">
      
              Yearly
      
              <span className="save-chip">
                Save 40%
              </span>
      
            </button>
      
          </div>
      
        </div>
      
        {/* ================= PRICING GRID ================= */}
      
        <div className="pricing-grid-preview">
      
          {/* FREE */}
      
          <div className="plan-card free-card">
      
            <div className="plan-name">
              Free
            </div>
      
            <p className="plan-tagline">
              For hobby projects
            </p>
      
            <div className="plan-price-wrap">
      
              <span className="plan-amount"
                data-month="$0"
                data-quarter="$0"
                data-year="$0">
      
                $0
      
              </span>
      
              <span className="plan-period">
                / month
              </span>
      
            </div>
      
            <ul className="plan-features">
      
              <li>
                <i className="fa-solid fa-check"></i>
                3 Projects
              </li>
      
              <li>
                <i className="fa-solid fa-check"></i>
                Community Support
              </li>
      
              <li>
                <i className="fa-solid fa-check"></i>
                Basic Analytics
              </li>
      
              <li className="muted">
                <i className="fa-solid fa-xmark"></i>
                Custom Domains
              </li>
      
              <li className="muted">
                <i className="fa-solid fa-xmark"></i>
                Priority Support
              </li>
      
            </ul>
      
            <button className="plan-btn plan-btn-outline">
              Get Started
            </button>
      
          </div>
      
          {/* PRO */}
      
          <div className="plan-card pro-card">
      
            <div className="recommended-badge">
      
              <i className="fa-solid fa-star"></i>
      
              Most Popular
      
            </div>
      
            <div className="plan-name">
              Pro
            </div>
      
            <p className="plan-tagline">
              Best for growing startups
            </p>
      
            <div className="plan-price-wrap">
      
              <span className="plan-old"
                data-month="$49"
                data-quarter="$44"
                data-year="$39">
      
                $49
      
              </span>
      
              <span className="plan-amount"
                data-month="$29"
                data-quarter="$26"
                data-year="$19">
      
                $29
      
              </span>
      
              <span className="plan-period">
                / month
              </span>
      
            </div>
      
            <ul className="plan-features">
      
              <li>
                <i className="fa-solid fa-check"></i>
                Unlimited Projects
              </li>
      
              <li>
                <i className="fa-solid fa-check"></i>
                Team Collaboration
              </li>
      
              <li>
                <i className="fa-solid fa-check"></i>
                Priority Support
              </li>
      
              <li>
                <i className="fa-solid fa-check"></i>
                Custom Domains
              </li>
      
              <li className="muted">
                <i className="fa-solid fa-xmark"></i>
                White Label
              </li>
      
            </ul>
      
            <button className="plan-btn plan-btn-accent">
              Choose Pro
            </button>
      
          </div>
      
          {/* ENTERPRISE */}
      
          <div className="plan-card enterprise-card">
      
            <div className="plan-name">
              Enterprise
            </div>
      
            <p className="plan-tagline">
              For large organizations
            </p>
      
            <div className="plan-price-wrap">
      
              <span className="plan-old"
                data-month="$149"
                data-quarter="$134"
                data-year="$119">
      
                $149
      
              </span>
      
              <span className="plan-amount"
                data-month="$99"
                data-quarter="$89"
                data-year="$69">
      
                $99
      
              </span>
      
              <span className="plan-period">
                / month
              </span>
      
            </div>
      
            <ul className="plan-features">
      
              <li>
                <i className="fa-solid fa-check"></i>
                Dedicated Manager
              </li>
      
              <li>
                <i className="fa-solid fa-check"></i>
                White Label
              </li>
      
              <li>
                <i className="fa-solid fa-check"></i>
                SLA Guarantee
              </li>
      
              <li>
                <i className="fa-solid fa-check"></i>
                Custom Integrations
              </li>
      
              <li>
                <i className="fa-solid fa-check"></i>
                Unlimited Storage
              </li>
      
            </ul>
      
            <button className="plan-btn business-btn">
              Contact Sales
            </button>
      
          </div>
      
        </div>
      
        {/* ================= ACTION BUTTONS ================= */}
      
        <div className="actions">
      
          <button className="action-btn view-btn"
            onclick="toggleCode('pc1', this)">
      
            <i className="fa-solid fa-code"></i>
            View Code
      
          </button>
      
          <button className="action-btn copy-btn"
            onclick="copyCode('pc1', this)">
      
            <i className="fa-solid fa-copy"></i>
            Copy
      
          </button>
      
        </div>
      
        {/* ================= CODE BLOCK ================= */}
      
        <pre id="pc1" className="code-block"><code>
      
      &lt;div className="pricing-grid-preview"&gt;
      
        &lt;div className="plan-card free-card"&gt;&lt;/div&gt;
      
        &lt;div className="plan-card pro-card"&gt;&lt;/div&gt;
      
        &lt;div className="plan-card enterprise-card"&gt;&lt;/div&gt;
      
      &lt;/div&gt;
      
        </code></pre>
      
      </div>
        
      
        {/* ================= ACTION BUTTONS ================= */}
      
        <div className="actions">
      
          <button className="action-btn view-btn"
            onclick="toggleCode('pc1', this)">
      
            <i className="fa-solid fa-code"></i>
            View Code
      
          </button>
      
          <button className="action-btn copy-btn"
            onclick="copyCode('pc1', this)">
      
            <i className="fa-solid fa-copy"></i>
            Copy
      
          </button>
      
        </div>
      
        {/* ================= CODE BLOCK ================= */}
      
        <pre id="pc1" className="code-block"><code>
      
      &lt;div className="pricing-grid-preview"&gt;
      
        &lt;div className="plan-card free-card"&gt;
          ...
        &lt;/div&gt;
      
        &lt;div className="plan-card pro-card"&gt;
          ...
        &lt;/div&gt;
      
        &lt;div className="plan-card enterprise-card"&gt;
          ...
        &lt;/div&gt;
      
      &lt;/div&gt;
      
        </code></pre>
      
      </div>
      
      {/* ================= SECOND COMPONENT ================= */}
      
      <div className="component-card">
      
        <div className="pricing-grid">
      
          {/* STARTER */}
          <div className="pricing-card starter">
      
            <div className="card-glow"></div>
      
            <div className="pricing-card-content">
      
              <div className="plan-header">
                <h3>Starter</h3>
                <p>Perfect for personal projects</p>
              </div>
      
              <div className="plan-price">
                <span className="old-price">$19</span>
                <span className="amount">$12</span>
              </div>
      
              <ul className="plan-features">
                <li><i className="fa-solid fa-check"></i> Basic analytics</li>
                <li><i className="fa-solid fa-check"></i> Custom domains</li>
                <li><i className="fa-solid fa-check"></i> Email support</li>
              </ul>
      
              <button className="plan-btn">
                Choose Starter
              </button>
      
            </div>
          </div>
      
          {/* PRO */}
          <div className="pricing-card pro featured">
      
            <div className="popular-badge">
              Most Popular
            </div>
      
            <div className="card-glow"></div>
      
            <div className="pricing-card-content">
      
              <div className="plan-header">
                <h3>Pro</h3>
                <p>Best for scaling your business</p>
              </div>
      
              <div className="plan-price">
                <span className="old-price">$49</span>
                <span className="amount">$29</span>
              </div>
      
              <ul className="plan-features">
                <li><i className="fa-solid fa-check"></i> Advanced analytics</li>
                <li><i className="fa-solid fa-check"></i> Unlimited projects</li>
                <li><i className="fa-solid fa-check"></i> Priority support</li>
                <li><i className="fa-solid fa-check"></i> Team collaboration</li>
              </ul>
      
              <button className="plan-btn secondary">
                Choose Pro
              </button>
      
            </div>
          </div>
      
          {/* BUSINESS */}
          <div className="pricing-card business">
      
            <div className="card-glow"></div>
      
            <div className="pricing-card-content">
      
              <div className="plan-header">
                <h3>Business</h3>
                <p>For growing startups & teams</p>
          
      
              <div className="plan-price">
                <span className="old-price">$99</span>
                <span className="amount">$59</span>
              </div>
      
              <ul className="plan-features">
                <li><i className="fa-solid fa-check"></i> AI-powered insights</li>
                <li><i className="fa-solid fa-check"></i> Unlimited storage</li>
                <li><i className="fa-solid fa-check"></i> Dedicated manager</li>
                <li><i className="fa-solid fa-check"></i> 24/7 live support</li>
              </ul>
      
              <button className="plan-btn business-btn">
                Choose Business
              </button>
      
            </div>
          </div>
      
        </div>
      
        {/* ACTIONS */}
        <div className="actions">
      
          <button className="action-btn view-btn"
            onclick="toggleCode('pc2', this)">
      
            <i className="fa-solid fa-code"></i>
            View Code
      
          </button>
      
          <button className="action-btn copy-btn"
            onclick="copyCode('pc2', this)">
      
            <i className="fa-solid fa-copy"></i>
            Copy
      
          </button>
      
        </div>
      
        {/* CODE */}
        <pre id="pc2" className="code-block"><code>
      
      &lt;div className="pricing-grid"&gt;
      
        &lt;div className="pricing-card starter"&gt;
          ...
        &lt;/div&gt;
      
        &lt;div className="pricing-card pro"&gt;
          ...
        &lt;/div&gt;
      
        &lt;div className="pricing-card business"&gt;
          ...
        &lt;/div&gt;
      
      &lt;/div&gt;
      
        </code></pre>
      
      </div>
       {/* /pricing-grid-preview */}
      
          
        
      
      </main>
    </>
  );
}
