// data/snippets/index/index.jsx
import React from 'react';

export default function index(){
  return (
    <>
      <main className="main-home">
      
        {/* ===== HERO ===== */}
        <section className="hero">
          <div className="hero-badge">🚀 v2.0 — Now with 120+ components</div>
      
          <h1 className="hero-title">
            Build <span className="hero-accent">beautiful UIs</span><br />
            in minutes, not hours.
          </h1>
      
          <p className="hero-desc">
            A curated library of reusable UI components crafted with pure HTML, CSS & JavaScript —
            no frameworks, no dependencies, just clean code.
          </p>
      
          <div className="hero-actions">
            <a href="button.html" className="btn-primary">
              Explore Components <i className="fa-solid fa-arrow-right"></i>
            </a>
            <a href="form.html" className="btn-ghost">
              Start Learning
            </a>
          </div>
      
          <div className="hero-stats">
            <div className="stat">
              <span className="stat-number">120+</span>
              <span className="stat-label">Components</span>
            </div>
            <div className="stat-divider"></div>
            <div className="stat">
              <span className="stat-number">8</span>
              <span className="stat-label">Categories</span>
            </div>
            <div className="stat-divider"></div>
            <div className="stat">
              <span className="stat-number">100%</span>
              <span className="stat-label">Free & Open Source</span>
            </div>
          </div>
      
          {/* floating orb decoration */}
          <div className="hero-orb orb-1"></div>
          <div className="hero-orb orb-2"></div>
        </section>
      
        {/* ===== POPULAR COMPONENTS ===== */}
        <section className="section featured-section">
          <div className="section-header">
            <span className="section-tag">Most Loved</span>
            <h2 className="section-title">⭐ Popular Components</h2>
            <p className="section-subtitle">Handpicked favorites from developers worldwide</p>
          </div>
      
          <div className="featured-cards">
      
            <div className="feature-card">
              <div className="feature-icon-wrap" style="--icon-color: #ff6b6b;">🎯</div>
              <div className="feature-card-body">
                <h3>Gradient Button</h3>
                <p>Modern colorful buttons with smooth gradient design.</p>
                <div className="feature-tags">
                  <span className="tag tag-popular">Popular</span>
                  <span className="tag tag-trending">Trending</span>
                </div>
              </div>
              <a href="button.html" className="feature-link">View <i className="fa-solid fa-arrow-right"></i></a>
            </div>
      
            <div className="feature-card">
              <div className="feature-icon-wrap" style="--icon-color: #74b9ff;">🎨</div>
              <div className="feature-card-body">
                <h3>Glass Navbar</h3>
                <p>Transparent blurred navigation bar with modern aesthetics.</p>
                <div className="feature-tags">
                  <span className="tag tag-popular">Popular</span>
                </div>
              </div>
              <a href="navbar.html" className="feature-link">View <i className="fa-solid fa-arrow-right"></i></a>
            </div>
      
            <div className="feature-card">
              <div className="feature-icon-wrap" style="--icon-color: #55efc4;">📦</div>
              <div className="feature-card-body">
                <h3>Card UI</h3>
                <p>Clean and reusable card layout for content display.</p>
                <div className="feature-tags">
                  <span className="tag tag-popular">Popular</span>
                </div>
              </div>
              <a href="cards.html" className="feature-link">View <i className="fa-solid fa-arrow-right"></i></a>
            </div>
      
            <div className="feature-card">
              <div className="feature-icon-wrap" style="--icon-color: #fdcb6e;">⚡</div>
              <div className="feature-card-body">
                <h3>Spinner Loaders</h3>
                <p>Smooth loading animations for better UX.</p>
                <div className="feature-tags">
                  <span className="tag tag-new">New</span>
                </div>
              </div>
              <a href="loaders.html" className="feature-link">View <i className="fa-solid fa-arrow-right"></i></a>
            </div>
      
            <div className="feature-card">
              <div className="feature-icon-wrap" style="--icon-color: #a29bfe;">💰</div>
              <div className="feature-card-body">
                <h3>Pricing Cards</h3>
                <p>Professional pricing sections for SaaS products.</p>
                <div className="feature-tags">
                  <span className="tag tag-popular">Popular</span>
                </div>
              </div>
              <a href="pricing.html" className="feature-link">View <i className="fa-solid fa-arrow-right"></i></a>
            </div>
      
            <div className="feature-card">
              <div className="feature-icon-wrap" style="--icon-color: #fd79a8;">🔔</div>
              <div className="feature-card-body">
                <h3>Alert Boxes</h3>
                <p>Responsive alert components for notifications.</p>
                <div className="feature-tags">
                  <span className="tag tag-essential">Essential</span>
                </div>
              </div>
              <a href="alerts.html" className="feature-link">View <i className="fa-solid fa-arrow-right"></i></a>
            </div>
      
            <div className="feature-card">
              <div className="feature-icon-wrap" style="--icon-color: #4ecdc4;">🌾</div>
              <div className="feature-card-body">
                <h3>Crop ROI Lab</h3>
                <p>Predict yield, revenue, and return on investment for the next harvest cycle.</p>
                <div className="feature-tags">
                  <span className="tag tag-new">New</span>
                  <span className="tag tag-essential">Finance</span>
                </div>
              </div>
              <a href="roi_dashboard.html" className="feature-link">View <i className="fa-solid fa-arrow-right"></i></a>
            </div>
      
            <div className="feature-card">
              <div className="feature-icon-wrap" style="--icon-color: #86c06a;">📦</div>
              <div className="feature-card-body">
                <h3>Produce Traceability</h3>
                <p>Generate a QR code for each batch and verify the full farm-to-shelf timeline.</p>
                <div className="feature-tags">
                  <span className="tag tag-new">New</span>
                  <span className="tag tag-essential">Supply Chain</span>
                </div>
              </div>
              <a href="trace.html" className="feature-link">View <i className="fa-solid fa-arrow-right"></i></a>
            </div>
      
            <div className="feature-card">
              <div className="feature-icon-wrap" style="--icon-color: #2f6f9f;">📡</div>
              <div className="feature-card-body">
                <h3>IoT Sensor Hub</h3>
                <p>Track moisture, temperature, humidity, and nutrient levels from connected farm sensors.</p>
                <div className="feature-tags">
                  <span className="tag tag-new">New</span>
                  <span className="tag tag-essential">Realtime</span>
                </div>
              </div>
              <a href="farm_dashboard.html" className="feature-link">View <i className="fa-solid fa-arrow-right"></i></a>
            </div>
      
            <div className="feature-card">
              <div className="feature-icon-wrap" style="--icon-color: #d97706;">🚜</div>
              <div className="feature-card-body">
                <h3>Equipment Marketplace</h3>
                <p>Share tractors and heavy machinery with neighboring farms through a rental marketplace.</p>
                <div className="feature-tags">
                  <span className="tag tag-new">New</span>
                  <span className="tag tag-essential">Sharing Economy</span>
                </div>
              </div>
              <a href="equipment.html" className="feature-link">View <i className="fa-solid fa-arrow-right"></i></a>
            </div>
      
          </div>
        </section>
      
        {/* ===== EXPLORE CATEGORIES ===== */}
        <section className="section categories-section">
          <div className="section-header">
            <span className="section-tag">Browse All</span>
            <h2 className="section-title">📦 Explore Categories</h2>
          </div>
      
          <div className="categories-grid">
            <a href="button.html" className="cat-card">
              <div className="cat-icon">🔘</div>
              <h3>Buttons</h3>
              <p>Interactive button styles</p>
              <span className="cat-count">24 items</span>
            </a>
            <a href="navbar.html" className="cat-card">
              <div className="cat-icon">☰</div>
              <h3>Navbars</h3>
              <p>Navigation UI components</p>
              <span className="cat-count">12 items</span>
            </a>
            <a href="cards.html" className="cat-card">
              <div className="cat-icon">🃏</div>
              <h3>Cards</h3>
              <p>Flexible card layouts</p>
              <span className="cat-count">18 items</span>
            </a>
            <a href="inputs.html" className="cat-card">
              <div className="cat-icon">⌨️</div>
              <h3>Inputs</h3>
              <p>Forms & input fields</p>
              <span className="cat-count">20 items</span>
            </a>
            <a href="forms.html" className="cat-card">
              <div className="cat-icon">📋</div>
              <h3>Forms</h3>
              <p>Complete form templates</p>
              <span className="cat-count">10 items</span>
            </a>
            <a href="roi_dashboard.html" className="cat-card">
              <div className="cat-icon">🌾</div>
              <h3>Finance Tools</h3>
              <p>Predict crop ROI and yield</p>
              <span className="cat-count">1 dashboard</span>
            </a>
            <a href="trace.html" className="cat-card">
              <div className="cat-icon">📦</div>
              <h3>Traceability</h3>
              <p>QR code and ledger verification</p>
              <span className="cat-count">2 pages</span>
            </a>
            <a href="farm_dashboard.html" className="cat-card">
              <div className="cat-icon">📡</div>
              <h3>IoT Hub</h3>
              <p>Realtime sensor telemetry</p>
              <span className="cat-count">2 pages</span>
            </a>
            <a href="equipment.html" className="cat-card">
              <div className="cat-icon">🚜</div>
              <h3>Equipment</h3>
              <p>Rental listings and booking</p>
              <span className="cat-count">2 pages</span>
            </a>
            <a href="badges.html" className="cat-card">
              <div className="cat-icon">🏅</div>
              <h3>Badges</h3>
              <p>Labels, tags & badges</p>
              <span className="cat-count">15 items</span>
            </a>
            <a href="color.html" className="cat-card">
              <div className="cat-icon">🎨</div>
              <h3>Colors</h3>
              <p>Color palette & themes</p>
              <span className="cat-count">8 items</span>
            </a>
            <a href="footer.html" className="cat-card">
              <div className="cat-icon">📄</div>
              <h3>Footers</h3>
              <p>Footer section layouts</p>
              <span className="cat-count">9 items</span>
            </a>
          </div>
        </section>
      
        {/* ===== WHY UIVERSE ===== */}
        <section className="section why-section">
          <div className="section-header">
            <span className="section-tag">Why choose us</span>
            <h2 className="section-title">✨ Why UIverse?</h2>
          </div>
      
          <div className="why-grid">
            <div className="why-card">
              <div className="why-icon">⚡</div>
              <h3>Fast & Lightweight</h3>
              <p>Zero frameworks, zero dependencies. Pure HTML, CSS and JavaScript for blazing fast performance.</p>
            </div>
            <div className="why-card">
              <div className="why-icon">📱</div>
              <h3>Fully Responsive</h3>
              <p>Every component is built mobile-first and works seamlessly on any device or screen size.</p>
            </div>
            <div className="why-card">
              <div className="why-icon">🎯</div>
              <h3>Beginner Friendly</h3>
              <p>Clean, well-commented code that's easy to understand, learn from, and customize.</p>
            </div>
            <div className="why-card">
              <div className="why-icon">🛠</div>
              <h3>Fully Customizable</h3>
              <p>Simple CSS variables make it trivial to adapt any component to match your brand.</p>
            </div>
            <div className="why-card">
              <div className="why-icon">🤝</div>
              <h3>Open Source</h3>
              <p>Everything is free and open source. Contribute, fork, or use however you like.</p>
            </div>
            <div className="why-card">
              <div className="why-icon">🔄</div>
              <h3>Regularly Updated</h3>
              <p>New components and improvements are added regularly. Stay ahead with the latest UI trends.</p>
            </div>
          </div>
        </section>
      
        {/* ===== CTA BANNER ===== */}
        <section className="cta-banner">
          <div className="cta-content">
            <h2>Ready to build something amazing?</h2>
            <p>Join thousands of developers already using UIverse components in their projects.</p>
            <a href="button.html" className="btn-primary">Get Started for Free <i className="fa-solid fa-rocket"></i></a>
          </div>
          <div className="cta-orb cta-orb-1"></div>
          <div className="cta-orb cta-orb-2"></div>
        </section>
      
      </main>
    </>
  );
}

// data/snippets/index/index.vue
<template>
<main class="main-home">

  <!-- ===== HERO ===== -->
  <section class="hero">
    <div class="hero-badge">🚀 v2.0 — Now with 120+ components</div>

    <h1 class="hero-title">
      Build <span class="hero-accent">beautiful UIs</span><br>
      in minutes, not hours.
    </h1>

    <p class="hero-desc">
      A curated library of reusable UI components crafted with pure HTML, CSS & JavaScript —
      no frameworks, no dependencies, just clean code.
    </p>

    <div class="hero-actions">
      <a href="button.html" class="btn-primary">
        Explore Components <i class="fa-solid fa-arrow-right"></i>
      </a>
      <a href="form.html" class="btn-ghost">
        Start Learning
      </a>
    </div>

    <div class="hero-stats">
      <div class="stat">
        <span class="stat-number">120+</span>
        <span class="stat-label">Components</span>
      </div>
      <div class="stat-divider"></div>
      <div class="stat">
        <span class="stat-number">8</span>
        <span class="stat-label">Categories</span>
      </div>
      <div class="stat-divider"></div>
      <div class="stat">
        <span class="stat-number">100%</span>
        <span class="stat-label">Free & Open Source</span>
      </div>
    </div>

    <!-- floating orb decoration -->
    <div class="hero-orb orb-1"></div>
    <div class="hero-orb orb-2"></div>
  </section>

  <!-- ===== POPULAR COMPONENTS ===== -->
  <section class="section featured-section">
    <div class="section-header">
      <span class="section-tag">Most Loved</span>
      <h2 class="section-title">⭐ Popular Components</h2>
      <p class="section-subtitle">Handpicked favorites from developers worldwide</p>
    </div>

    <div class="featured-cards">

      <div class="feature-card">
        <div class="feature-icon-wrap" style="--icon-color: #ff6b6b;">🎯</div>
        <div class="feature-card-body">
          <h3>Gradient Button</h3>
          <p>Modern colorful buttons with smooth gradient design.</p>
          <div class="feature-tags">
            <span class="tag tag-popular">Popular</span>
            <span class="tag tag-trending">Trending</span>
          </div>
        </div>
        <a href="button.html" class="feature-link">View <i class="fa-solid fa-arrow-right"></i></a>
      </div>

      <div class="feature-card">
        <div class="feature-icon-wrap" style="--icon-color: #74b9ff;">🎨</div>
        <div class="feature-card-body">
          <h3>Glass Navbar</h3>
          <p>Transparent blurred navigation bar with modern aesthetics.</p>
          <div class="feature-tags">
            <span class="tag tag-popular">Popular</span>
          </div>
        </div>
        <a href="navbar.html" class="feature-link">View <i class="fa-solid fa-arrow-right"></i></a>
      </div>

      <div class="feature-card">
        <div class="feature-icon-wrap" style="--icon-color: #55efc4;">📦</div>
        <div class="feature-card-body">
          <h3>Card UI</h3>
          <p>Clean and reusable card layout for content display.</p>
          <div class="feature-tags">
            <span class="tag tag-popular">Popular</span>
          </div>
        </div>
        <a href="cards.html" class="feature-link">View <i class="fa-solid fa-arrow-right"></i></a>
      </div>

      <div class="feature-card">
        <div class="feature-icon-wrap" style="--icon-color: #fdcb6e;">⚡</div>
        <div class="feature-card-body">
          <h3>Spinner Loaders</h3>
          <p>Smooth loading animations for better UX.</p>
          <div class="feature-tags">
            <span class="tag tag-new">New</span>
          </div>
        </div>
        <a href="loaders.html" class="feature-link">View <i class="fa-solid fa-arrow-right"></i></a>
      </div>

      <div class="feature-card">
        <div class="feature-icon-wrap" style="--icon-color: #a29bfe;">💰</div>
        <div class="feature-card-body">
          <h3>Pricing Cards</h3>
          <p>Professional pricing sections for SaaS products.</p>
          <div class="feature-tags">
            <span class="tag tag-popular">Popular</span>
          </div>
        </div>
        <a href="pricing.html" class="feature-link">View <i class="fa-solid fa-arrow-right"></i></a>
      </div>

      <div class="feature-card">
        <div class="feature-icon-wrap" style="--icon-color: #fd79a8;">🔔</div>
        <div class="feature-card-body">
          <h3>Alert Boxes</h3>
          <p>Responsive alert components for notifications.</p>
          <div class="feature-tags">
            <span class="tag tag-essential">Essential</span>
          </div>
        </div>
        <a href="alerts.html" class="feature-link">View <i class="fa-solid fa-arrow-right"></i></a>
      </div>

      <div class="feature-card">
        <div class="feature-icon-wrap" style="--icon-color: #4ecdc4;">🌾</div>
        <div class="feature-card-body">
          <h3>Crop ROI Lab</h3>
          <p>Predict yield, revenue, and return on investment for the next harvest cycle.</p>
          <div class="feature-tags">
            <span class="tag tag-new">New</span>
            <span class="tag tag-essential">Finance</span>
          </div>
        </div>
        <a href="roi_dashboard.html" class="feature-link">View <i class="fa-solid fa-arrow-right"></i></a>
      </div>

      <div class="feature-card">
        <div class="feature-icon-wrap" style="--icon-color: #86c06a;">📦</div>
        <div class="feature-card-body">
          <h3>Produce Traceability</h3>
          <p>Generate a QR code for each batch and verify the full farm-to-shelf timeline.</p>
          <div class="feature-tags">
            <span class="tag tag-new">New</span>
            <span class="tag tag-essential">Supply Chain</span>
          </div>
        </div>
        <a href="trace.html" class="feature-link">View <i class="fa-solid fa-arrow-right"></i></a>
      </div>

      <div class="feature-card">
        <div class="feature-icon-wrap" style="--icon-color: #2f6f9f;">📡</div>
        <div class="feature-card-body">
          <h3>IoT Sensor Hub</h3>
          <p>Track moisture, temperature, humidity, and nutrient levels from connected farm sensors.</p>
          <div class="feature-tags">
            <span class="tag tag-new">New</span>
            <span class="tag tag-essential">Realtime</span>
          </div>
        </div>
        <a href="farm_dashboard.html" class="feature-link">View <i class="fa-solid fa-arrow-right"></i></a>
      </div>

      <div class="feature-card">
        <div class="feature-icon-wrap" style="--icon-color: #d97706;">🚜</div>
        <div class="feature-card-body">
          <h3>Equipment Marketplace</h3>
          <p>Share tractors and heavy machinery with neighboring farms through a rental marketplace.</p>
          <div class="feature-tags">
            <span class="tag tag-new">New</span>
            <span class="tag tag-essential">Sharing Economy</span>
          </div>
        </div>
        <a href="equipment.html" class="feature-link">View <i class="fa-solid fa-arrow-right"></i></a>
      </div>

    </div>
  </section>

  <!-- ===== EXPLORE CATEGORIES ===== -->
  <section class="section categories-section">
    <div class="section-header">
      <span class="section-tag">Browse All</span>
      <h2 class="section-title">📦 Explore Categories</h2>
    </div>

    <div class="categories-grid">
      <a href="button.html" class="cat-card">
        <div class="cat-icon">🔘</div>
        <h3>Buttons</h3>
        <p>Interactive button styles</p>
        <span class="cat-count">24 items</span>
      </a>
      <a href="navbar.html" class="cat-card">
        <div class="cat-icon">☰</div>
        <h3>Navbars</h3>
        <p>Navigation UI components</p>
        <span class="cat-count">12 items</span>
      </a>
      <a href="cards.html" class="cat-card">
        <div class="cat-icon">🃏</div>
        <h3>Cards</h3>
        <p>Flexible card layouts</p>
        <span class="cat-count">18 items</span>
      </a>
      <a href="inputs.html" class="cat-card">
        <div class="cat-icon">⌨️</div>
        <h3>Inputs</h3>
        <p>Forms & input fields</p>
        <span class="cat-count">20 items</span>
      </a>
      <a href="forms.html" class="cat-card">
        <div class="cat-icon">📋</div>
        <h3>Forms</h3>
        <p>Complete form templates</p>
        <span class="cat-count">10 items</span>
      </a>
      <a href="roi_dashboard.html" class="cat-card">
        <div class="cat-icon">🌾</div>
        <h3>Finance Tools</h3>
        <p>Predict crop ROI and yield</p>
        <span class="cat-count">1 dashboard</span>
      </a>
      <a href="trace.html" class="cat-card">
        <div class="cat-icon">📦</div>
        <h3>Traceability</h3>
        <p>QR code and ledger verification</p>
        <span class="cat-count">2 pages</span>
      </a>
      <a href="farm_dashboard.html" class="cat-card">
        <div class="cat-icon">📡</div>
        <h3>IoT Hub</h3>
        <p>Realtime sensor telemetry</p>
        <span class="cat-count">2 pages</span>
      </a>
      <a href="equipment.html" class="cat-card">
        <div class="cat-icon">🚜</div>
        <h3>Equipment</h3>
        <p>Rental listings and booking</p>
        <span class="cat-count">2 pages</span>
      </a>
      <a href="badges.html" class="cat-card">
        <div class="cat-icon">🏅</div>
        <h3>Badges</h3>
        <p>Labels, tags & badges</p>
        <span class="cat-count">15 items</span>
      </a>
      <a href="color.html" class="cat-card">
        <div class="cat-icon">🎨</div>
        <h3>Colors</h3>
        <p>Color palette & themes</p>
        <span class="cat-count">8 items</span>
      </a>
      <a href="footer.html" class="cat-card">
        <div class="cat-icon">📄</div>
        <h3>Footers</h3>
        <p>Footer section layouts</p>
        <span class="cat-count">9 items</span>
      </a>
    </div>
  </section>

  <!-- ===== WHY UIVERSE ===== -->
  <section class="section why-section">
    <div class="section-header">
      <span class="section-tag">Why choose us</span>
      <h2 class="section-title">✨ Why UIverse?</h2>
    </div>

    <div class="why-grid">
      <div class="why-card">
        <div class="why-icon">⚡</div>
        <h3>Fast & Lightweight</h3>
        <p>Zero frameworks, zero dependencies. Pure HTML, CSS and JavaScript for blazing fast performance.</p>
      </div>
      <div class="why-card">
        <div class="why-icon">📱</div>
        <h3>Fully Responsive</h3>
        <p>Every component is built mobile-first and works seamlessly on any device or screen size.</p>
      </div>
      <div class="why-card">
        <div class="why-icon">🎯</div>
        <h3>Beginner Friendly</h3>
        <p>Clean, well-commented code that's easy to understand, learn from, and customize.</p>
      </div>
      <div class="why-card">
        <div class="why-icon">🛠</div>
        <h3>Fully Customizable</h3>
        <p>Simple CSS variables make it trivial to adapt any component to match your brand.</p>
      </div>
      <div class="why-card">
        <div class="why-icon">🤝</div>
        <h3>Open Source</h3>
        <p>Everything is free and open source. Contribute, fork, or use however you like.</p>
      </div>
      <div class="why-card">
        <div class="why-icon">🔄</div>
        <h3>Regularly Updated</h3>
        <p>New components and improvements are added regularly. Stay ahead with the latest UI trends.</p>
      </div>
    </div>
  </section>

  <!-- ===== CTA BANNER ===== -->
  <section class="cta-banner">
    <div class="cta-content">
      <h2>Ready to build something amazing?</h2>
      <p>Join thousands of developers already using UIverse components in their projects.</p>
      <a href="button.html" class="btn-primary">Get Started for Free <i class="fa-solid fa-rocket"></i></a>
    </div>
    <div class="cta-orb cta-orb-1"></div>
    <div class="cta-orb cta-orb-2"></div>
  </section>

</main>
</template>

<script>
export default { name: 'Index' }
</script>
