// data/snippets/table/table.jsx
import React from 'react';

export default function table(){
  return (
    <>
      <main className="main-home">
      
      {/* HERO */}
      <section className="section">
        <h1>📊 Advanced Tables Dashboard</h1>
        <p>Modern SaaS-style responsive tables with real-world datasets.</p>
      </section>
      
      {/* ================= TABLE 1 ================= */}
      <section className="section">
        <h2>👨‍💼 Employee Directory</h2>
      
        <div className="table-wrapper">
          <table className="ui-table">
            <thead>
              <tr>
                <th>ID</th><th>Name</th><th>Role</th><th>Dept</th><th>Status</th>
              </tr>
            </thead>
      
            <tbody>
              <tr><td>01</td><td>Arjun Mehta</td><td>Frontend Dev</td><td>Eng</td><td>Active</td></tr>
              <tr><td>02</td><td>Meera Das</td><td>UI Designer</td><td>Design</td><td>Active</td></tr>
              <tr><td>03</td><td>Rahul Sharma</td><td>Backend Dev</td><td>Eng</td><td>Active</td></tr>
              <tr><td>04</td><td>Sneha Roy</td><td>PM</td><td>Product</td><td>Active</td></tr>
              <tr><td>05</td><td>Vikram Singh</td><td>DevOps</td><td>Infra</td><td>Inactive</td></tr>
              <tr><td>06</td><td>Ishita Jain</td><td>Analyst</td><td>Data</td><td>Active</td></tr>
              <tr><td>07</td><td>Karan Mehta</td><td>ML Eng</td><td>AI</td><td>Active</td></tr>
            </tbody>
          </table>
        </div>
      </section>
      
      {/* ================= TABLE 2 ================= */}
      <section className="section">
        <h2>🧑‍💻 User Management</h2>
      
        <div className="table-wrapper">
          <table className="ui-table">
            <thead>
              <tr>
                <th>User</th><th>Email</th><th>Role</th><th>Status</th>
              </tr>
            </thead>
      
            <tbody>
              <tr><td>Aryan Sharma</td><td>aryan@mail.com</td><td>Admin</td><td>Active</td></tr>
              <tr><td>Meera Das</td><td>meera@mail.com</td><td>User</td><td>Pending</td></tr>
              <tr><td>John Carter</td><td>john@mail.com</td><td>Editor</td><td>Inactive</td></tr>
              <tr><td>Priya Nair</td><td>priya@mail.com</td><td>User</td><td>Active</td></tr>
              <tr><td>Rohan Verma</td><td>rohan@mail.com</td><td>Admin</td><td>Active</td></tr>
              <tr><td>Anjali Singh</td><td>anjali@mail.com</td><td>Editor</td><td>Active</td></tr>
            </tbody>
          </table>
        </div>
      </section>
      
      {/* ================= TABLE 3 ================= */}
      <section className="section">
        <h2>📊 Analytics Team</h2>
      
        <div className="table-wrapper">
          <table className="ui-table">
            <thead>
              <tr>
                <th>Name</th><th>Role</th><th>Projects</th><th>Rating</th>
              </tr>
            </thead>
      
            <tbody>
              <tr><td>Neha Gupta</td><td>Data Scientist</td><td>8</td><td>★★★★★</td></tr>
              <tr><td>Rohan Verma</td><td>ML Engineer</td><td>6</td><td>★★★★</td></tr>
              <tr><td>Priya Nair</td><td>AI Engineer</td><td>5</td><td>★★★★★</td></tr>
              <tr><td>Karan Mehta</td><td>Data Eng</td><td>7</td><td>★★★★</td></tr>
              <tr><td>Ishita Jain</td><td>Analyst</td><td>10</td><td>★★★★★</td></tr>
              <tr><td>Sneha Roy</td><td>Product</td><td>9</td><td>★★★★★</td></tr>
            </tbody>
          </table>
        </div>
      </section>
      
      {/* ================= TABLE 4 ================= */}
      <section className="section">
        <h2>💰 Payroll System</h2>
      
        <div className="table-wrapper">
          <table className="ui-table">
            <thead>
              <tr>
                <th>Name</th><th>Dept</th><th>Salary</th><th>Attendance</th>
              </tr>
            </thead>
      
            <tbody>
              <tr><td>Arjun</td><td>Eng</td><td>₹80,000</td><td>95%</td></tr>
              <tr><td>Meera</td><td>Design</td><td>₹65,000</td><td>88%</td></tr>
              <tr><td>Rahul</td><td>Backend</td><td>₹90,000</td><td>92%</td></tr>
              <tr><td>Sneha</td><td>Product</td><td>₹1,00,000</td><td>97%</td></tr>
              <tr><td>Vikram</td><td>DevOps</td><td>₹85,000</td><td>70%</td></tr>
            </tbody>
          </table>
        </div>
      </section>
      
      {/* ================= TABLE 5 ================= */}
      <section className="section">
        <h2>📁 Project Tracker</h2>
      
        <div className="table-wrapper">
          <table className="ui-table">
            <thead>
              <tr>
                <th>Project</th><th>Manager</th><th>Team</th><th>Status</th>
              </tr>
            </thead>
      
            <tbody>
              <tr><td>E-Commerce</td><td>Arjun</td><td>8</td><td>Active</td></tr>
              <tr><td>AI Chatbot</td><td>Priya</td><td>5</td><td>Pending</td></tr>
              <tr><td>CRM System</td><td>Rahul</td><td>6</td><td>Completed</td></tr>
              <tr><td>Portfolio UI</td><td>Sneha</td><td>4</td><td>Active</td></tr>
              <tr><td>Analytics</td><td>Karan</td><td>10</td><td>Delayed</td></tr>
            </tbody>
          </table>
        </div>
      </section>
      
      {/* ================= TABLE 6 ================= */}
      <section className="section">
        <h2>💳 Transactions</h2>
      
        <div className="table-wrapper">
          <table className="ui-table">
            <thead>
              <tr>
                <th>TXN ID</th><th>User</th><th>Method</th><th>Amount</th><th>Status</th>
              </tr>
            </thead>
      
            <tbody>
              <tr><td>#101</td><td>Arjun</td><td>UPI</td><td>₹2,500</td><td>Success</td></tr>
              <tr><td>#102</td><td>Meera</td><td>Card</td><td>₹1,200</td><td>Pending</td></tr>
              <tr><td>#103</td><td>Rahul</td><td>NetBank</td><td>₹5,000</td><td>Success</td></tr>
              <tr><td>#104</td><td>Sneha</td><td>UPI</td><td>₹750</td><td>Failed</td></tr>
              <tr><td>#105</td><td>Vikram</td><td>Card</td><td>₹9,000</td><td>Success</td></tr>
            </tbody>
          </table>
        </div>
      </section>
      
      {/* ================= TABLE 8 ================= */}
      <section className="section">
        <h2>📈 Sales Performance Dashboard</h2>
      
        <div className="table-wrapper">
          <table className="ui-table modern-table">
            <thead>
              <tr>
                <th>Sales Rep</th>
                <th>Region</th>
                <th>Revenue</th>
                <th>Deals Closed</th>
                <th>Growth</th>
                <th>Status</th>
              </tr>
            </thead>
      
            <tbody>
              <tr>
                <td>
                  <div className="table-user">
                    <img src="https://i.pravatar.cc/80?img=15" alt="" />
                    <span>Emma Watson</span>
                  </div>
                </td>
                <td>North America</td>
                <td>$82,400</td>
                <td>41</td>
                <td className="positive">+18%</td>
                <td><span className="badge success">Top Performer</span></td>
              </tr>
      
              <tr>
                <td>
                  <div className="table-user">
                    <img src="https://i.pravatar.cc/80?img=21" alt="" />
                    <span>David Lee</span>
                  </div>
                </td>
                <td>Europe</td>
                <td>$65,200</td>
                <td>35</td>
                <td className="positive">+11%</td>
                <td><span className="badge active">Active</span></td>
              </tr>
      
              <tr>
                <td>
                  <div className="table-user">
                    <img src="https://i.pravatar.cc/80?img=31" alt="" />
                    <span>Sophia Turner</span>
                  </div>
                </td>
                <td>Asia</td>
                <td>$92,000</td>
                <td>48</td>
                <td className="positive">+25%</td>
                <td><span className="badge success">Excellent</span></td>
              </tr>
      
            </tbody>
          </table>
        </div>
      </section>
      
      {/* ================= TABLE 9 ================= */}
      <section className="section">
        <h2>🚀 Startup Investment Portfolio</h2>
      
        <div className="table-wrapper">
          <table className="ui-table glass-table">
            <thead>
              <tr>
                <th>Startup</th>
                <th>Industry</th>
                <th>Funding</th>
                <th>Investors</th>
                <th>Stage</th>
                <th>ROI</th>
              </tr>
            </thead>
      
            <tbody>
              <tr>
                <td>NeuroAI</td>
                <td>Artificial Intelligence</td>
                <td>$5M</td>
                <td>12</td>
                <td>Series A</td>
                <td className="positive">+48%</td>
              </tr>
      
              <tr>
                <td>EcoGrid</td>
                <td>Clean Energy</td>
                <td>$2.8M</td>
                <td>7</td>
                <td>Seed</td>
                <td className="positive">+23%</td>
              </tr>
      
              <tr>
                <td>HealthSync</td>
                <td>Healthcare</td>
                <td>$9.2M</td>
                <td>15</td>
                <td>Series B</td>
                <td className="negative">-4%</td>
              </tr>
      
            </tbody>
          </table>
        </div>
      </section>
      
      {/* ================= TABLE 10 ================= */}
      <section className="section">
        <h2>🛒 E-Commerce Orders</h2>
      
        <div className="table-wrapper">
          <table className="ui-table ecommerce-table">
            <thead>
              <tr>
                <th>Order</th>
                <th>Customer</th>
                <th>Product</th>
                <th>Price</th>
                <th>Delivery</th>
                <th>Payment</th>
              </tr>
            </thead>
      
            <tbody>
              <tr>
                <td>#ORD-1291</td>
                <td>Olivia Brown</td>
                <td>MacBook Pro</td>
                <td>$2,499</td>
                <td><span className="badge success">Delivered</span></td>
                <td><span className="badge active">Paid</span></td>
              </tr>
      
              <tr>
                <td>#ORD-1292</td>
                <td>James Wilson</td>
                <td>Gaming Monitor</td>
                <td>$799</td>
                <td><span className="badge pending">Shipping</span></td>
                <td><span className="badge success">Paid</span></td>
              </tr>
      
              <tr>
                <td>#ORD-1293</td>
                <td>Charlotte Hall</td>
                <td>iPhone 17</td>
                <td>$1,399</td>
                <td><span className="badge danger">Delayed</span></td>
                <td><span className="badge active">Paid</span></td>
              </tr>
      
            </tbody>
          </table>
        </div>
      </section>
      
      {/* ================= TABLE 11 ================= */}
      <section className="section">
        <h2>🌍 Global Traffic Sources</h2>
      
        <div className="table-wrapper">
          <table className="ui-table premium-table">
            <thead>
              <tr>
                <th>Source</th>
                <th>Visitors</th>
                <th>Bounce Rate</th>
                <th>Avg. Time</th>
                <th>Conversion</th>
              </tr>
            </thead>
      
            <tbody>
              <tr>
                <td>Organic Search</td>
                <td>182K</td>
                <td>34%</td>
                <td>4m 22s</td>
                <td>8.4%</td>
              </tr>
      
              <tr>
                <td>Social Media</td>
                <td>94K</td>
                <td>42%</td>
                <td>2m 51s</td>
                <td>4.2%</td>
              </tr>
      
              <tr>
                <td>Email Campaign</td>
                <td>38K</td>
                <td>19%</td>
                <td>6m 10s</td>
                <td>14.7%</td>
              </tr>
      
              <tr>
                <td>Referral</td>
                <td>61K</td>
                <td>27%</td>
                <td>3m 42s</td>
                <td>7.1%</td>
              </tr>
      
            </tbody>
          </table>
        </div>
      </section>
      
      {/* ================= TABLE 12 ================= */}
      <section className="section">
        <h2>🧠 AI Model Leaderboard</h2>
      
        <div className="table-wrapper">
          <table className="ui-table neon-table">
            <thead>
              <tr>
                <th>Model</th>
                <th>Accuracy</th>
                <th>Latency</th>
                <th>Dataset</th>
                <th>Rank</th>
              </tr>
            </thead>
      
            <tbody>
              <tr>
                <td>GPT-X Ultra</td>
                <td>98.7%</td>
                <td>0.8s</td>
                <td>WebScale-9</td>
                <td>🥇</td>
              </tr>
      
              <tr>
                <td>VisionNet AI</td>
                <td>96.1%</td>
                <td>1.2s</td>
                <td>ImageNet++</td>
                <td>🥈</td>
              </tr>
      
              <tr>
                <td>Quantum NLP</td>
                <td>94.4%</td>
                <td>1.8s</td>
                <td>MultiLang-XL</td>
                <td>🥉</td>
              </tr>
      
            </tbody>
          </table>
        </div>
      </section>
      
      {/* ================= TABLE 7 ================= */}
      <section className="section">
        <h2>🎧 Support Tickets</h2>
      
        <div className="table-wrapper">
          <table className="ui-table">
            <thead>
              <tr>
                <th>Ticket</th><th>User</th><th>Issue</th><th>Priority</th><th>Status</th>
              </tr>
            </thead>
      
            <tbody>
              <tr><td>#T1</td><td>Arjun</td><td>Login Issue</td><td>High</td><td>Open</td></tr>
              <tr><td>#T2</td><td>Meera</td><td>Payment Bug</td><td>Medium</td><td>Progress</td></tr>
              <tr><td>#T3</td><td>Rahul</td><td>UI Bug</td><td>Low</td><td>Resolved</td></tr>
              <tr><td>#T4</td><td>Sneha</td><td>Account Locked</td><td>High</td><td>Open</td></tr>
            </tbody>
          </table>
        </div>
      </section>
      
      </main>
    </>
  );
}

// data/snippets/table/table.vue
<template>
<main class="main-home">

<!-- HERO -->
<section class="section">
  <h1>📊 Advanced Tables Dashboard</h1>
  <p>Modern SaaS-style responsive tables with real-world datasets.</p>
</section>

<!-- ================= TABLE 1 ================= -->
<section class="section">
  <h2>👨‍💼 Employee Directory</h2>

  <div class="table-wrapper">
    <table class="ui-table">
      <thead>
        <tr>
          <th>ID</th><th>Name</th><th>Role</th><th>Dept</th><th>Status</th>
        </tr>
      </thead>

      <tbody>
        <tr><td>01</td><td>Arjun Mehta</td><td>Frontend Dev</td><td>Eng</td><td>Active</td></tr>
        <tr><td>02</td><td>Meera Das</td><td>UI Designer</td><td>Design</td><td>Active</td></tr>
        <tr><td>03</td><td>Rahul Sharma</td><td>Backend Dev</td><td>Eng</td><td>Active</td></tr>
        <tr><td>04</td><td>Sneha Roy</td><td>PM</td><td>Product</td><td>Active</td></tr>
        <tr><td>05</td><td>Vikram Singh</td><td>DevOps</td><td>Infra</td><td>Inactive</td></tr>
        <tr><td>06</td><td>Ishita Jain</td><td>Analyst</td><td>Data</td><td>Active</td></tr>
        <tr><td>07</td><td>Karan Mehta</td><td>ML Eng</td><td>AI</td><td>Active</td></tr>
      </tbody>
    </table>
  </div>
</section>

<!-- ================= TABLE 2 ================= -->
<section class="section">
  <h2>🧑‍💻 User Management</h2>

  <div class="table-wrapper">
    <table class="ui-table">
      <thead>
        <tr>
          <th>User</th><th>Email</th><th>Role</th><th>Status</th>
        </tr>
      </thead>

      <tbody>
        <tr><td>Aryan Sharma</td><td>aryan@mail.com</td><td>Admin</td><td>Active</td></tr>
        <tr><td>Meera Das</td><td>meera@mail.com</td><td>User</td><td>Pending</td></tr>
        <tr><td>John Carter</td><td>john@mail.com</td><td>Editor</td><td>Inactive</td></tr>
        <tr><td>Priya Nair</td><td>priya@mail.com</td><td>User</td><td>Active</td></tr>
        <tr><td>Rohan Verma</td><td>rohan@mail.com</td><td>Admin</td><td>Active</td></tr>
        <tr><td>Anjali Singh</td><td>anjali@mail.com</td><td>Editor</td><td>Active</td></tr>
      </tbody>
    </table>
  </div>
</section>

<!-- ================= TABLE 3 ================= -->
<section class="section">
  <h2>📊 Analytics Team</h2>

  <div class="table-wrapper">
    <table class="ui-table">
      <thead>
        <tr>
          <th>Name</th><th>Role</th><th>Projects</th><th>Rating</th>
        </tr>
      </thead>

      <tbody>
        <tr><td>Neha Gupta</td><td>Data Scientist</td><td>8</td><td>★★★★★</td></tr>
        <tr><td>Rohan Verma</td><td>ML Engineer</td><td>6</td><td>★★★★</td></tr>
        <tr><td>Priya Nair</td><td>AI Engineer</td><td>5</td><td>★★★★★</td></tr>
        <tr><td>Karan Mehta</td><td>Data Eng</td><td>7</td><td>★★★★</td></tr>
        <tr><td>Ishita Jain</td><td>Analyst</td><td>10</td><td>★★★★★</td></tr>
        <tr><td>Sneha Roy</td><td>Product</td><td>9</td><td>★★★★★</td></tr>
      </tbody>
    </table>
  </div>
</section>

<!-- ================= TABLE 4 ================= -->
<section class="section">
  <h2>💰 Payroll System</h2>

  <div class="table-wrapper">
    <table class="ui-table">
      <thead>
        <tr>
          <th>Name</th><th>Dept</th><th>Salary</th><th>Attendance</th>
        </tr>
      </thead>

      <tbody>
        <tr><td>Arjun</td><td>Eng</td><td>₹80,000</td><td>95%</td></tr>
        <tr><td>Meera</td><td>Design</td><td>₹65,000</td><td>88%</td></tr>
        <tr><td>Rahul</td><td>Backend</td><td>₹90,000</td><td>92%</td></tr>
        <tr><td>Sneha</td><td>Product</td><td>₹1,00,000</td><td>97%</td></tr>
        <tr><td>Vikram</td><td>DevOps</td><td>₹85,000</td><td>70%</td></tr>
      </tbody>
    </table>
  </div>
</section>

<!-- ================= TABLE 5 ================= -->
<section class="section">
  <h2>📁 Project Tracker</h2>

  <div class="table-wrapper">
    <table class="ui-table">
      <thead>
        <tr>
          <th>Project</th><th>Manager</th><th>Team</th><th>Status</th>
        </tr>
      </thead>

      <tbody>
        <tr><td>E-Commerce</td><td>Arjun</td><td>8</td><td>Active</td></tr>
        <tr><td>AI Chatbot</td><td>Priya</td><td>5</td><td>Pending</td></tr>
        <tr><td>CRM System</td><td>Rahul</td><td>6</td><td>Completed</td></tr>
        <tr><td>Portfolio UI</td><td>Sneha</td><td>4</td><td>Active</td></tr>
        <tr><td>Analytics</td><td>Karan</td><td>10</td><td>Delayed</td></tr>
      </tbody>
    </table>
  </div>
</section>

<!-- ================= TABLE 6 ================= -->
<section class="section">
  <h2>💳 Transactions</h2>

  <div class="table-wrapper">
    <table class="ui-table">
      <thead>
        <tr>
          <th>TXN ID</th><th>User</th><th>Method</th><th>Amount</th><th>Status</th>
        </tr>
      </thead>

      <tbody>
        <tr><td>#101</td><td>Arjun</td><td>UPI</td><td>₹2,500</td><td>Success</td></tr>
        <tr><td>#102</td><td>Meera</td><td>Card</td><td>₹1,200</td><td>Pending</td></tr>
        <tr><td>#103</td><td>Rahul</td><td>NetBank</td><td>₹5,000</td><td>Success</td></tr>
        <tr><td>#104</td><td>Sneha</td><td>UPI</td><td>₹750</td><td>Failed</td></tr>
        <tr><td>#105</td><td>Vikram</td><td>Card</td><td>₹9,000</td><td>Success</td></tr>
      </tbody>
    </table>
  </div>
</section>

<!-- ================= TABLE 8 ================= -->
<section class="section">
  <h2>📈 Sales Performance Dashboard</h2>

  <div class="table-wrapper">
    <table class="ui-table modern-table">
      <thead>
        <tr>
          <th>Sales Rep</th>
          <th>Region</th>
          <th>Revenue</th>
          <th>Deals Closed</th>
          <th>Growth</th>
          <th>Status</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>
            <div class="table-user">
              <img src="https://i.pravatar.cc/80?img=15" alt="">
              <span>Emma Watson</span>
            </div>
          </td>
          <td>North America</td>
          <td>$82,400</td>
          <td>41</td>
          <td class="positive">+18%</td>
          <td><span class="badge success">Top Performer</span></td>
        </tr>

        <tr>
          <td>
            <div class="table-user">
              <img src="https://i.pravatar.cc/80?img=21" alt="">
              <span>David Lee</span>
            </div>
          </td>
          <td>Europe</td>
          <td>$65,200</td>
          <td>35</td>
          <td class="positive">+11%</td>
          <td><span class="badge active">Active</span></td>
        </tr>

        <tr>
          <td>
            <div class="table-user">
              <img src="https://i.pravatar.cc/80?img=31" alt="">
              <span>Sophia Turner</span>
            </div>
          </td>
          <td>Asia</td>
          <td>$92,000</td>
          <td>48</td>
          <td class="positive">+25%</td>
          <td><span class="badge success">Excellent</span></td>
        </tr>

      </tbody>
    </table>
  </div>
</section>

<!-- ================= TABLE 9 ================= -->
<section class="section">
  <h2>🚀 Startup Investment Portfolio</h2>

  <div class="table-wrapper">
    <table class="ui-table glass-table">
      <thead>
        <tr>
          <th>Startup</th>
          <th>Industry</th>
          <th>Funding</th>
          <th>Investors</th>
          <th>Stage</th>
          <th>ROI</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>NeuroAI</td>
          <td>Artificial Intelligence</td>
          <td>$5M</td>
          <td>12</td>
          <td>Series A</td>
          <td class="positive">+48%</td>
        </tr>

        <tr>
          <td>EcoGrid</td>
          <td>Clean Energy</td>
          <td>$2.8M</td>
          <td>7</td>
          <td>Seed</td>
          <td class="positive">+23%</td>
        </tr>

        <tr>
          <td>HealthSync</td>
          <td>Healthcare</td>
          <td>$9.2M</td>
          <td>15</td>
          <td>Series B</td>
          <td class="negative">-4%</td>
        </tr>

      </tbody>
    </table>
  </div>
</section>

<!-- ================= TABLE 10 ================= -->
<section class="section">
  <h2>🛒 E-Commerce Orders</h2>

  <div class="table-wrapper">
    <table class="ui-table ecommerce-table">
      <thead>
        <tr>
          <th>Order</th>
          <th>Customer</th>
          <th>Product</th>
          <th>Price</th>
          <th>Delivery</th>
          <th>Payment</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>#ORD-1291</td>
          <td>Olivia Brown</td>
          <td>MacBook Pro</td>
          <td>$2,499</td>
          <td><span class="badge success">Delivered</span></td>
          <td><span class="badge active">Paid</span></td>
        </tr>

        <tr>
          <td>#ORD-1292</td>
          <td>James Wilson</td>
          <td>Gaming Monitor</td>
          <td>$799</td>
          <td><span class="badge pending">Shipping</span></td>
          <td><span class="badge success">Paid</span></td>
        </tr>

        <tr>
          <td>#ORD-1293</td>
          <td>Charlotte Hall</td>
          <td>iPhone 17</td>
          <td>$1,399</td>
          <td><span class="badge danger">Delayed</span></td>
          <td><span class="badge active">Paid</span></td>
        </tr>

      </tbody>
    </table>
  </div>
</section>

<!-- ================= TABLE 11 ================= -->
<section class="section">
  <h2>🌍 Global Traffic Sources</h2>

  <div class="table-wrapper">
    <table class="ui-table premium-table">
      <thead>
        <tr>
          <th>Source</th>
          <th>Visitors</th>
          <th>Bounce Rate</th>
          <th>Avg. Time</th>
          <th>Conversion</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>Organic Search</td>
          <td>182K</td>
          <td>34%</td>
          <td>4m 22s</td>
          <td>8.4%</td>
        </tr>

        <tr>
          <td>Social Media</td>
          <td>94K</td>
          <td>42%</td>
          <td>2m 51s</td>
          <td>4.2%</td>
        </tr>

        <tr>
          <td>Email Campaign</td>
          <td>38K</td>
          <td>19%</td>
          <td>6m 10s</td>
          <td>14.7%</td>
        </tr>

        <tr>
          <td>Referral</td>
          <td>61K</td>
          <td>27%</td>
          <td>3m 42s</td>
          <td>7.1%</td>
        </tr>

      </tbody>
    </table>
  </div>
</section>

<!-- ================= TABLE 12 ================= -->
<section class="section">
  <h2>🧠 AI Model Leaderboard</h2>

  <div class="table-wrapper">
    <table class="ui-table neon-table">
      <thead>
        <tr>
          <th>Model</th>
          <th>Accuracy</th>
          <th>Latency</th>
          <th>Dataset</th>
          <th>Rank</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>GPT-X Ultra</td>
          <td>98.7%</td>
          <td>0.8s</td>
          <td>WebScale-9</td>
          <td>🥇</td>
        </tr>

        <tr>
          <td>VisionNet AI</td>
          <td>96.1%</td>
          <td>1.2s</td>
          <td>ImageNet++</td>
          <td>🥈</td>
        </tr>

        <tr>
          <td>Quantum NLP</td>
          <td>94.4%</td>
          <td>1.8s</td>
          <td>MultiLang-XL</td>
          <td>🥉</td>
        </tr>

      </tbody>
    </table>
  </div>
</section>

<!-- ================= TABLE 7 ================= -->
<section class="section">
  <h2>🎧 Support Tickets</h2>

  <div class="table-wrapper">
    <table class="ui-table">
      <thead>
        <tr>
          <th>Ticket</th><th>User</th><th>Issue</th><th>Priority</th><th>Status</th>
        </tr>
      </thead>

      <tbody>
        <tr><td>#T1</td><td>Arjun</td><td>Login Issue</td><td>High</td><td>Open</td></tr>
        <tr><td>#T2</td><td>Meera</td><td>Payment Bug</td><td>Medium</td><td>Progress</td></tr>
        <tr><td>#T3</td><td>Rahul</td><td>UI Bug</td><td>Low</td><td>Resolved</td></tr>
        <tr><td>#T4</td><td>Sneha</td><td>Account Locked</td><td>High</td><td>Open</td></tr>
      </tbody>
    </table>
  </div>
</section>

</main>
</template>

<script>
export default { name: 'Table' }
</script>
